name: locami
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  country_picker: ^2.0.27
  flutter:
    sdk: flutter
  flutter_typeahead: ^5.2.0
  geolocator: ^14.0.2
  get: ^4.7.3
  http: ^1.6.0
  path: ^1.9.1
  provider: ^6.1.5+1
  sensors_plus: ^6.1.2
  sqflite: ^2.4.2
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
dependency_overrides:
  package_info_plus: 8.0.2
